component: nextjs
name: nextjsDemo
org: orgDemo
app: appDemo
stage: dev

inputs:
  src:
    src: ./
    exclude:
      - .env
  region: ap-chengdu
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
