component: nextjs
name: nextjsDemo
org: orgDemo
app: appDemo
stage: dev

inputs:
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: Nodejs10.15
  layers:
    - name: nextjs-demo #  layer名称
      version: 1 #  版本
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
